from ase.units import Hartree, Bohr
from ase.io import read, Trajectory
from glob import glob

def parse_energies(string):
    for line in string.splitlines():
        if 'TOTAL' in line:
            # Total Energy in eV
            e = float(line.split()[-3]) * Hartree

    return e

def parse_ipea_homolumo(string):
    """Parse IP/EA aswell as HOMO/LUMO for comparison
    First HOMO/LUMO instance in stdout corresponds to neutral molecule as calculated with IPEA parametetized GFN1-xTB.
    HOMO/LUMO with regular GFN1-xTB differs but since IPEA parameterized version is better suited for IP/EA,
    it might correspondingly better descirbe HOMO/LUMO"""
    homo_parsed, lumo_parsed = False, False
    for line in string.splitlines():
        if 'delta SCC IP (eV)' in line:
            # ionization potential in eV
            ip = float(line.split()[-1])
        if 'delta SCC EA (eV)' in line:
            # electron affinity in eV
            ea = float(line.split()[-1])
        if '(HOMO)' in line and not homo_parsed:
            # KS Homo in eV
            homo = float(line.split()[-2])
            homo_parsed = True
        if '(LUMO)' in line and not lumo_parsed:
            # KS Lumo in eV
            lumo = float(line.split()[-2])
            lumo_parsed = True

    return ip, ea, homo, lumo

def parse_zpe(string):
    for line in string.splitlines():
        if 'zero point energy' in line:
            zpe_ = float(line.split()[4]) * Hartree # in eV
            return zpe_

def parse_stdoutput(xtb_output, runtype):
    # Standard output from xtb call is parsed according to runtype
    d = dict()
    if runtype == 'sp' or 'opt' in runtype:
        d['energy'] = parse_energies(xtb_output)
    elif runtype == 'hess':
        d['zpe'] = parse_zpe(xtb_output)
        # Thermo parsing
    elif runtype == 'vipea':
        d['ip'], d['ea'], d['ehomo'], d['elumo'] = parse_ipea_homolumo(xtb_output)

    return d

def xtboptlog_to_ase_trajectory(optimization_log_path):
    # Convert an optimization log generated by 'xtb --opt' to an ASE trajectory .traj file
    # for easy viewing with 'ase gui *.traj' in commandline
    opt_steps = read(optimization_log_path, format='xyz', index=':')
    trajectory_log_path = optimization_log_path.replace('.log', '.traj')

    with Trajectory(trajectory_log_path, 'w') as t:
        for step in opt_steps:
            t.write(step)

def create_trajectories_from_logs(path):
    # Look for xtbopt.log files in 'path' and create .traj files
    path_of_optlogs = glob(f"{path}/**/xtbopt.log", recursive=True) # absolute paths

    for p in path_of_optlogs:
        xtboptlog_to_ase_trajectory(p)